export const types  = {
    GET_MODELS : '[Model] GET_MODELS',
    GET_MODEL : '[Model] GET_MODEL',
    GET_MODELS_TOTAL : '[Model] GET_MODELS_TOTAL',
    GET_MODELS_TOTAL_PAGES : '[Model] GET_MODELS_TOTAL_PAGES',
    ADD_MODEL_CART : '[Model] ADD_MODEL_CART',
    DELETE_MODEL_CART : '[Model] DELETE_MODEL_CART',
    EMPTY_CART :'[Model] EMPTY_CART',
}